worlds:
    new world:
    - AUJRW0V64
    - K7I9FI3XY
    - K5BDXSZIS
    - FFOELAW6O
    - REGAPK231
    - MFRGPEPUK
    - QHPCB8ZQ1
    - WYHBPTV09
    - ECE6GI5EU
    - ZICO7JW82
    - DUULEQUX0
    - 4UOW2P33T
    new world default:
    - K4UXR91N7
    - 598YLXM79
