worlds:
    new world:
    - AUJRW0V64
    - K7I9FI3XY
    - FFOELAW6O
    - REGAPK231
    - QHPCB8ZQ1
    - WYHBPTV09
    - ECE6GI5EU
    - K5BDXSZIS
    - MFRGPEPUK
    - ZICO7JW82
    - DUULEQUX0
    - 4UOW2P33T
    - OAIW8LEXG
    new world default:
    - K4UXR91N7
    - 598YLXM79
    new world rtg:
    - U7PUZC6FP
    - I1JOZUCIX
    new world456+4+5:
    - I4TVR5YNS
    new worldshfrzfgshg:
    - AT1PCJL53
